In [1]:
import pandas as pd
import requests
import time

In [2]:
import requests

url = "https://community-open-weather-map.p.rapidapi.com/weather"

querystring = {"q":"portugal","lang":"eng","units":"metric"}

headers = {
	"X-RapidAPI-Host": "community-open-weather-map.p.rapidapi.com",
	"X-RapidAPI-Key": "5f923a0d42msh3a49a095d38db66p176833jsne813ae937562"
}

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.json())

{'coord': {'lon': -8, 'lat': 39.5}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'base': 'stations', 'main': {'temp': 16.2, 'feels_like': 15.73, 'temp_min': 10.01, 'temp_max': 16.57, 'pressure': 1023, 'humidity': 71, 'sea_level': 1023, 'grnd_level': 1009}, 'visibility': 10000, 'wind': {'speed': 2.18, 'deg': 17, 'gust': 4.01}, 'clouds': {'all': 22}, 'dt': 1651184364, 'sys': {'type': 2, 'id': 2001942, 'country': 'PT', 'sunrise': 1651124213, 'sunset': 1651173713}, 'timezone': 3600, 'id': 2264397, 'name': 'Portugal', 'cod': 200}

In [3]:
response.content

b'{"coord":{"lon":-8,"lat":39.5},"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02n"}],"base":"stations","main":{"temp":16.2,"feels_like":15.73,"temp_min":10.01,"temp_max":16.57,"pressure":1023,"humidity":71,"sea_level":1023,"grnd_level":1009},"visibility":10000,"wind":{"speed":2.18,"deg":17,"gust":4.01},"clouds":{"all":22},"dt":1651184364,"sys":{"type":2,"id":2001942,"country":"PT","sunrise":1651124213,"sunset":1651173713},"timezone":3600,"id":2264397,"name":"Portugal","cod":200}'

In [4]:
weather_data=(response.json())

name  = weather_data["name"]
weather = weather_data['weather'][0]['main']
temp = weather_data['main']['temp']

In [5]:
data = []

data.append({'Country' : name, 'Weather' : weather, 'Temperature' : temp})

pd.DataFrame(data)

    Country Weather  Temperature
0  Portugal  Clouds         16.2

In [6]:
countries = ['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia and territories',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Republic of the Congo',
 'Democratic Republic of the Congo',
 'Costa Rica',
 "Côte d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'East Timor',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'North Korea',
 'South Korea',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'São Tomé and Príncipe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom and Crown dependencies',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [12]:
country = "Albania"
data = []


url = "https://community-open-weather-map.p.rapidapi.com/weather"

querystring = {"q":country,"lang":"eng","units":"metric"}

headers = {
    "X-RapidAPI-Host": "community-open-weather-map.p.rapidapi.com",
    "X-RapidAPI-Key": "5f923a0d42msh3a49a095d38db66p176833jsne813ae937562"
    }

print(country)
response = requests.request("GET", url, headers=headers, params=querystring)
time.sleep(4)

weather_data=(response.json())

name  = weather_data["name"]
weather = weather_data['weather'][0]['main']
temp = weather_data['main']['temp']

data.append({'Country' : name, 'Weather' : weather, 'Temperature' : temp})
   

Forecast=pd.DataFrame(data)

Albania

In [18]:
int(Forecast["Temperature"])

14

In [ ]:

data = []

for country in countries:
    try:
        url = "https://community-open-weather-map.p.rapidapi.com/weather"

        querystring = {"q":country,"lang":"eng","units":"metric"}

        headers = {
            "X-RapidAPI-Host": "community-open-weather-map.p.rapidapi.com",
            "X-RapidAPI-Key": "5f923a0d42msh3a49a095d38db66p176833jsne813ae937562"
        }

        print(country)
        response = requests.request("GET", url, headers=headers, params=querystring)
        time.sleep(4)

        weather_data=(response.json())

        name  = weather_data["name"]
        weather = weather_data['weather'][0]['main']
        temp = weather_data['main']['temp']

        data.append({'Country' : name, 'Weather' : weather, 'Temperature' : temp})
    except:
        pass

Forecast=pd.DataFrame(data)

In [10]:
Forecast

    Country Weather  Temperature
0   Albania  Clouds        15.73
1   Albania   Clear        14.35
2   Albania   Clear        24.98
3   Albania  Clouds        10.62
4   Albania  Clouds        19.50
5   Albania  Clouds        24.32
6   Albania   Clear        11.93
7   Albania  Clouds         9.42
8   Albania   Clear        -0.65
9   Albania  Clouds        14.15
10  Albania  Clouds        25.89
11  Albania  Clouds        26.73
12  Albania  Clouds        23.20
13  Albania   Clear        19.98
14  Albania  Clouds         2.01
15  Albania   Clear        12.33
16  Albania    Rain        11.29
17  Albania  Clouds        19.23
18  Albania  Clouds        -3.21
19  Albania  Clouds        25.99
20  Albania    Rain        21.91
21  Albania   Clear        31.49
22  Albania  Clouds        25.33
23  Albania  Clouds         7.53
24  Albania  Clouds        25.63
25  Albania  Clouds        26.99
26  Albania  Clouds         0.73
27  Albania    Rain        20.89
28  Albania    Rain         4.30
29  Albania  Clouds        25.01
30  Albania   Clear         3.75
31  Albania    Rain        23.43
32  Albania   Clear        27.98
33  Albania   Clear         7.63
34  Albania  Clouds         4.51
35  Albania  Clouds         9.02
36  Albania  Clouds        11.20
37  Albania  Clouds        14.75
38  Albania    Rain        21.61
39  Albania  Clouds        29.34
40  Albania  Clouds        26.37
41  Albania  Clouds        28.08
42  Albania  Clouds        18.89
43  Albania  Clouds        13.40
44  Albania   Clear        21.65
45  Albania  Clouds        31.03
46  Albania  Clouds        17.84
47  Albania  Clouds        10.36
48  Albania  Clouds        28.16
49  Albania  Clouds        19.80
50  Albania   Clear        10.46